// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NRP_EvalPluginCommand","status":true,"description":"v1.03 プラグインコマンドで数式や制御文字を使用可能に","parameters":{"enableEvaluate":"false"}},
{"name":"LL_ActorChoicesMV","status":true,"description":"アクターを選択するプラグインコマンドを実装します。","parameters":{"selectActorListMasters":"[]","cancelLabel":"キャンセル","cancelPosition":"bottom"}},
{"name":"MNKR_SkillChoiceScene","status":true,"description":"スキル選択シーンとスキルの増減のプラグインコマンドを追加します。","parameters":{"windowX":"0","windowY":"0","windowWidth":"0","windowHeight":"0"}},
{"name":"MNKR_SkillChoice","status":false,"description":"スキル選択の処理とスキルの増減のプラグインコマンドを追加します。","parameters":{}},
{"name":"TMEventItemEx","status":false,"description":"アイテム選択の処理にヘルプウィンドウを追加し、個数表示の有無と表示行数をアイテムタイプごとに設定できます。","parameters":{"helpWindowEnabledItem":"true","helpWindowEnabledKey":"true","helpWindowEnabledA":"true","helpWindowEnabledB":"true","showItemNumberItem":"true","showItemNumberKey":"true","showItemNumberA":"true","showItemNumberB":"true","numVisibleRowsItem":"4","numVisibleRowsKey":"4","numVisibleRowsA":"4","numVisibleRowsB":"4","fixPlacement":"top"}}
];
